---
- name: Running TEC05 test role on the S4/HANA Cluster
  hosts: all
  gather_facts: false
  become: true
  become_user: root
  tasks:
    - name: Testing pcs_status_info module
      sap.sap_operations.pcs_status_info:
      register: pcs_status_post_enq_kill
      until: "(pcs_status_post_enq_kill.pacemaker_status['pacemaker-result'].failures | default([]) | length == 0)"
      delay: 5
      retries: 10