---
- name: Running TEST05 test role on the S4/HANA Cluster
  hosts: all
  gather_facts: false
  become: true
  become_user: root
  tasks:
    - name: Running TEST05 test role on the S4/HANA Cluster
      ansible.builtin.include_role:
        name: sap.cluster_qa.tec05
