---
galaxy_info:
  author: Amir Memon (@amemon-redhat)
  description: Ensure that HANA cluster is initialized for QA testing
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  license: GPL-3.0-only
  galaxy_tags: []
dependencies: []
