---
- name: Playbook for testing HDB kill and failover
  hosts: all
  tasks:
    - name: Acquiring Replication sync state
      shell: "crm_mon -A1 | grep 'Node Attributes' -A24 | grep hana_{{ sap_hana_sid | lower }}_sync_state"
      register: sap_hana_sync_state_t4

    - name: Verifying SOK state before performing test
      debug:
        msg: "SAP HANA Replication sync state is {{ sap_hana_sync_state_t4.stdout }}"
      failed_when: "'SOK' not in sap_hana_sync_state_t4.stdout"

    - name: PERFORMING HDB kill on MASTER node
      become: yes
      become_user: "{{ sap_hana_sid|lower }}adm"
      shell: "/usr/sap/{{ sap_hana_sid }}/HDB{{ sap_hana_instance_number }}/HDB kill"
      delegate_to: "{{ sap_hana_master_node }}"
      run_once: true
      register: sap_hana_master_node_hdb_killed

    - name: Verifying that HDB is fully killed
      delegate_to: "{{ sap_hana_master_node }}"
      run_once: true
      until: "'killing HDB processes' in sap_hana_master_node_hdb_killed.stdout"
      debug:
        msg: "Success message \"killing HDB processes\" observed"
      failed_when: "'killing HDB processes' not in sap_hana_master_node_hdb_killed.stdout"
      retries: 10
      delay: 5

    - name: Waiting for Cluster to declare failure and start recovery
      shell: pcs status | grep "Failed Resource Actions" -A1
      register: sap_hana_master_monitor_operation_failed
      delegate_to: "{{ sap_hana_master_node }}"
      run_once: true
      until: "'Failed Resource Actions' in sap_hana_master_monitor_operation_failed.stdout"
      retries: 120
      delay: 5

    - name: WAITING for recovery to complete on the same node
      shell: pcs resource status | grep "{{ sap_hana_resource_name }}" -A1 | tail -n1 | xargs
      register: sap_hana_resource_recovery_state
      delegate_to: "{{ sap_hana_master_node }}"
      run_once: true
      until: "'Masters:' in sap_hana_resource_recovery_state.stdout"
      when: "'PREFER_SITE_TAKEOVER=false' in prefer_site_takeover"
      retries: 120
      delay: 5

    - name: VERIFYING the recovery on same node
      debug:
        msg: "Current state of resource recovery is {{ sap_hana_resource_recovery_state.stdout }}"
      when: "'PREFER_SITE_TAKEOVER=false' in prefer_site_takeover"
      failed_when: "'Masters:' and sap_hana_master_node not in sap_hana_resource_recovery_state.stdout"   

    - name: Cleaning up cluster for next test
      shell: pcs resource cleanup "{{ sap_hana_resource_name }}"
      run_once: true
      delegate_to: "{{ sap_hana_master_node }}"
      when: "'PREFER_SITE_TAKEOVER=false' in prefer_site_takeover"

    - name: WAITING for promotion to complete on the other node
      shell: pcs resource status | grep "{{ sap_hana_resource_name }}" -A1 | tail -n1 | xargs
      register: sap_hana_resource_recovery_state
      delegate_to: "{{ sap_hana_slave_node }}"
      run_once: true
      until: "'Masters:' in sap_hana_resource_recovery_state.stdout"
      when: "'PREFER_SITE_TAKEOVER=true' in prefer_site_takeover"
      retries: 120
      delay: 5

    - name: VERIFYING promotion of the slave node
      debug:
        msg: "Current state of resource recovery is {{ sap_hana_resource_recovery_state.stdout }}"
      when: "'PREFER_SITE_TAKEOVER=true' in prefer_site_takeover"
      failed_when: "'Masters:' and sap_hana_slave_node not in sap_hana_resource_recovery_state.stdout"

    - name: Cleaning up cluster for next test
      shell: pcs resource cleanup "{{ sap_hana_resource_name }}"
      run_once: true
      delegate_to: "{{ sap_hana_slave_node }}"
      when: "'PREFER_SITE_TAKEOVER=true' in prefer_site_takeover"

