---
- name: Setting PREFER_SITE_TAKEOVER value to false
  hosts: all
  tasks:
    - name: Setting up PREFER_SITE_TAKEOVER value to false
      ansible.builtin.command: "pcs resource update {{ sap_hana_resource_name }} AUTOMATED_REGISTER=true PREFER_SITE_TAKEOVER=true"
      delegate_to: "{{ sap_hana_master_node }}"
      run_once: true
