---
- name: Playbook to test the working state of the Pacemaker HANA cluster Nodes
  hosts: all
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 102-ar-to-tru-pstv-to-tru.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 02-fence-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 03-hdb-stop-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 04-hdb-kill-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 05-node-crash-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 08-cluster-network-down-tests.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 100-pstv-to-fls.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 02-fence-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 03-hdb-stop-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 04-hdb-kill-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 05-node-crash-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 08-cluster-network-down-tests.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 101-ar-to-fls-pstv-to-tru.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 02-fence-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 03-hdb-stop-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 04-hdb-kill-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 05-node-crash-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 08-cluster-network-down-tests.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 100-pstv-to-fls.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 02-fence-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 03-hdb-stop-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 04-hdb-kill-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 05-node-crash-test.yml
- import_playbook: 01-acquire-and-set-facts.yml
- import_playbook: 08-cluster-network-down-tests.yml
- import_playbook: 01-acquire-and-set-facts.yml
