---
- name: Acquiring SAP HA trace logs.
  ansible.builtin.shell: |
    set -o pipefail |
    cat "/usr/sap/{{ sap_sid.stdout }}/{{ sap_instance_name }}/work/sapstartsrv.log" |
    grep "SAP HA Trace" |
    tail -n 50
  register: ha_trace_logs

- name: Printing SAP HA trace logs.
  ansible.builtin.debug:
    msg: "{{ ha_trace_logs.stdout_lines }}"
