---
driver:
  name: default
platforms:
  - name: s4hana17-amemon
    ip: 192.168.5.191
  - name: s4hana18-amemon
    ip: 192.168.5.192
  - name: s4hana19-amemon
    ip: 192.168.5.193

scenario:
  converge_sequence:
    - create
    - prepare
    - converge
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - destroy
  destroy_sequence:
    - destroy

provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    destroy: ../default/destroy.yml
