---
galaxy_info:
  author: Amir Memon (@amemon-redhat)
  description: Find if SAP ASCS instance is running on the host
  license: GPL-3.0-only
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"

  galaxy_tags: []
dependencies: []
