---
- name: Collection information about SAP instances installed on the current instance
  sap.sap_operations.ha_get_failoverconfig_info:
    instance_number: "{{ sap_instance_number }}"
  become: true
  become_user: root
  register: test01_failoverconfig_info

- name: Print test results completing TEST01 test case for current instance
  ansible.builtin.debug:
    msg: "{{ test01_failoverconfig_info }}"
  failed_when: >
    (test01_failoverconfig_info.ha_get_failoverconfig_info.HAActive == false)
    or
    (test01_failoverconfig_info.ha_get_failoverconfig_info.HAActiveNode is none)
    or
    (test01_failoverconfig_info.ha_get_failoverconfig_info.HADocumentation is none)
    or
    (test01_failoverconfig_info.ha_get_failoverconfig_info.HAProductVersion is none)
    or
    (test01_failoverconfig_info.ha_get_failoverconfig_info.HASAPInterfaceVersion is none)
