---
- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure VMs are running
      ovirt.ovirt.ovirt_vm:
        auth:
          insecure: true
        name: "{{ platform.name }}"
        state: running
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        loop_var: platform
      register: server

    - name: Get info about VMs
      ovirt.ovirt.ovirt_vm_info:
        auth:
          insecure: true
        pattern: "name={{ platform.name }}"
        all_content: true
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        loop_var: platform
      register: server_info

    - name: Print server
      ansible.builtin.debug:
        msg: "{{ server_info }}"

    - name: Create instance config
      block:
        - name: Populate instance config dict # noqa jinja
          ansible.builtin.set_fact:
            instance_conf_dict:
              instance: "{{ item.ovirt_vms[0].fqdn}}"
              address: "{{ item.ovirt_vms[0].fqdn}}"
              user: molecule
              port: 22
              identity_file: ~/.ssh/id_molecule_rsa
          with_items: "{{ server_info.results }}"
          register: instance_config_dict

        - name: Convert instance config dict to a list
          ansible.builtin.set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Dump instance config
          ansible.builtin.copy:
            content: |
              # Molecule managed

              {{ instance_conf | to_json | from_json | to_yaml }}
            dest: "{{ molecule_instance_config }}"
            mode: "0600"
