---
- name: Destroy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure VMs are running
      ovirt.ovirt.ovirt_vm:
        auth:
          insecure: true
        name: "{{ platform.name }}"
        state: stopped
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: platform

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
      when: server.changed | default(false) | bool # noqa no-handler
