---

galaxy_info:
  author: Amir Memon (@amemon)

  description: your role description

  license: GPL-3.0-only

  min_ansible_version: "2.14"

  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"

  galaxy_tags: []

dependencies: []
