---
- name: Create Power
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create instance config
      block:
        - name: Populate instance config dict
          ansible.builtin.set_fact:
            instance_conf_dict:
              instance: "{{ platform.name }}"
              address: "{{ platform.ip }}"
              user: molecule
              port: 22
              identity_file: ~/.ssh/id_molecule_rsa
          loop: "{{ molecule_yml.platforms }}"
          loop_control:
            loop_var: platform
          register: instance_config_dict

        - name: Dump instance config
          ansible.builtin.copy:
            content: |
              # Molecule managed

              {{ instance_conf | to_json | from_json | to_yaml }}
            dest: "{{ molecule_instance_config }}"
            mode: "0600"
          vars:
            instance_conf: "\
              {{ instance_config_dict.results | \
              map(attribute='ansible_facts.instance_conf_dict') | list }}"
