---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Starting the cluster
      ansible.builtin.shell: |
        pcs cluster start --all
        pcs cluster enable --all
      become: true
      become_user: root
      changed_when: false
