---
driver:
  name: default
platforms:
  - name: lsh40410
    ip: 10.98.84.201
  - name: lsh40411
    ip: 10.98.84.202
  - name: lsh40412
    ip: 10.98.84.203

scenario:
  converge_sequence:
    - create
    - prepare
    - converge
  test_sequence:
    - create
    - prepare
    - converge
    - destroy
  destroy_sequence:
    - destroy

provisioner:
  name: ansible
  playbooks:
    create: ../default/create_power.yml
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    destroy: ""
