---

galaxy_info:
  author: Amir Memon
  description: Verification of HA software delivery
  company: Red Hat

  license: GPL-3.0-only

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"

  galaxy_tags: []

dependencies: []
