---
galaxy_info:
  author: Amir Memon (@amemon-redhat)
  description: Run test10 - Irrecoverable Message Server outage test (Start_Program)
  license: GPL-3.0-only
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
  galaxy_tags: []
dependencies: []
