name: molecule

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request_target:
    types: [opened, synchronize, reopened]

env:
  WORKDIR: ansible_collections/sap/cluster_qa/roles/tec02
  PYTHON_VERSION: "3.10"

jobs:
  molecule-tec02:
    runs-on: sap-ha-cluster

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create molecule ssh key
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_molecule_rsa
          touch ~/.ssh/id_molecule_rsa.pub
          chmod 600 ~/.ssh/id_molecule_rsa
          chmod 600 ~/.ssh/id_molecule_rsa.pub
          echo "$ID_MOLECULE_RSA" | base64 --decode > ~/.ssh/id_molecule_rsa
          echo "$ID_MOLECULE_RSA_PUB" > ~/.ssh/id_molecule_rsa.pub
          chmod 400 ~/.ssh/id_molecule_rsa
          chmod 400 ~/.ssh/id_molecule_rsa.pub

        env:
          ID_MOLECULE_RSA: ${{ secrets.ID_MOLECULE_RSA }}
          ID_MOLECULE_RSA_PUB: ${{ secrets.ID_MOLECULE_RSA_PUB }}

      - name: Run molecule
        continue-on-error: true
        run: |
          source ~/.bashrc
          pyenv install ${PYTHON_VERSION} || true
          pyenv global ${PYTHON_VERSION}
          pyenv rehash
          python --version
          make -- molecule test
        env:
          OVIRT_HOSTNAME: ${{ secrets.OVIRT_HOSTNAME }}
          OVIRT_USERNAME: ${{ secrets.OVIRT_USERNAME }}
          OVIRT_PASSWORD: ${{ secrets.OVIRT_PASSWORD }}

      # - name: Remove molecule ssh key
      #   run: |
      #     rm -f ~/.ssh/id_molecule_rsa
      #     rm -f ~/.ssh/id_molecule_rsa.pub
