name: molecule

on:
  workflow_dispatch
  push:
    branches: [main]
  pull_request_target:
    types: [opened, synchronize, reopened]

env:
  WORKDIR: ansible_collections/sap/cluster_qa/roles/tec02
  PYTHON_VERSION: "3.10"

jobs:
  molecule-tec02:
    runs-on: sap-ha-cluster

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run molecule
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv virtualenv-init -)"
          pyenv install ${PYTHON_VERSION} || true
          pyenv global ${PYTHON_VERSION}
          pyenv rehash
          python --version
          make -- molecule test
        env:
          OVIRT_HOSTNAME: ${{ secrets.OVIRT_HOSTNAME }}
          OVIRT_USERNAME: ${{ secrets.OVIRT_USERNAME }}
          OVIRT_PASSWORD: ${{ secrets.OVIRT_USERNAME }}
