---
galaxy_info:
  author: Amir Memon (@amemon-redhat)
  description: Run test08 - Hardware failure simulation test by crashing ASCS node
  license: GPl-3.0-only
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags: []
dependencies: []
